#! /bin/bash
case "$1" in
    "unpack") 
        echo "Mirroring files from diskstation: ...";
        rclone sync --progress diskstation:/PARA/Projects ~/Mirror/Projects;
        rclone sync --progress diskstation:/PARA/Areas ~/Mirror/Areas;;
    "pack") 
        echo "Pushing local changes to diskstation: ...";
        rclone sync --progress ~/Mirror/Projects diskstation:/PARA/Projects;
        rclone sync --progress ~/Mirror/Areas diskstation:/PARA/Areas;;
    "status") 
        echo "Comparing diskstation: to local mirror ...";
        rclone check diskstation:/PARA/Projects ~/Mirror/Projects;
        rclone check diskstation:/PARA/Areas ~/Mirror/Areas;;
    *) 
        echo "Invalid parameter: Use unpack, pack or status.";; 
esac
